name: Cloudflare IPs Rewrite

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Cloudflare_IPs_rewrite:
    name: Cloudflare IPs Rewrite
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Checking
        run: bash src/check_cf_ips.sh
        env:
          nextdns_api: ${{ secrets.NEXTDNS_API }}
          profile_id: ${{ secrets.PROFILE_ID }}
          repository: ${{ github.repository }}
      - name: Rewritting
        run: bash src/cf_ips.sh
        env:
          nextdns_api: ${{ secrets.NEXTDNS_API }}
          profile_id: ${{ secrets.PROFILE_ID }}
          repository: ${{ github.repository }}
          exclude_domain: ${{ vars.EXCLUDE_DOMAIN }}
          include_domain: ${{ vars.INCLUDE_DOMAIN }}
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: |
          /storage/*.txt
        name: Test
        tag: all
        allowUpdates: true